use crate::{
    FusionBackend, FusionDevice, FusionHandle, FusionRuntime, FusionServer, FusionTensor,
    UnfusedOp,
    stream::{OperationStreams, StreamId, execution::Operation},
};
#[cfg(feature = "distributed")]
use burn_backend::distributed::DistributedBackend;
use burn_backend::{Device, DeviceHandle, DeviceId, DeviceService, DeviceServiceStage};
use burn_backend::{TensorData, backend::ExecutionError};
use burn_ir::{OperationIr, TensorId, TensorIr};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

/// Use a mutex to communicate with the fusion server.
pub struct GlobalFusionClient<R: FusionRuntime> {
    server: DeviceHandle<FusionServer<R>>,
    device: FusionDevice<R>,
}

impl<R: FusionRuntime> DeviceService for FusionServer<R> {
    fn init(device_id: DeviceId) -> Self {
        let device = FusionDevice::<R>::from_id(device_id);
        FusionServer::new(device)
    }

    fn utilities(&self) -> burn_backend::ServerUtilitiesHandle {
        Arc::new(())
    }
    fn stage() -> DeviceServiceStage {
        DeviceServiceStage::Upstream
    }
}

impl<R> Clone for GlobalFusionClient<R>
where
    R: FusionRuntime,
{
    fn clone(&self) -> Self {
        Self {
            server: self.server.clone(),
            device: self.device.clone(),
        }
    }
}
impl<R> GlobalFusionClient<R>
where
    R: FusionRuntime + 'static,
{
    /// Loads the client from the given device.
    pub fn load(device: &FusionDevice<R>) -> Self {
        Self {
            device: device.clone(),
            server: DeviceHandle::new(device.to_id()),
        }
    }
}

static COUNTER: AtomicU64 = AtomicU64::new(0);

impl<R> GlobalFusionClient<R>
where
    R: FusionRuntime + 'static,
{
    /// Create a new client for the given [device](FusionRuntime::FusionDevice).
    pub fn new(device: FusionDevice<R>) -> Self {
        Self {
            device: device.clone(),
            server: DeviceHandle::new(device.to_id()),
        }
    }

    /// Register a new [tensor operation intermediate representation](OperationIr).
    ///
    /// Returns the new (uninitialized) output tensor(s) generated by the registered operation.
    pub fn register<O>(
        &self,
        streams: OperationStreams,
        repr: OperationIr,
        operation: O,
    ) -> Vec<FusionTensor<R>>
    where
        O: Operation<R> + 'static,
    {
        // Create output tensors returned by this operation
        let outputs = repr
            .outputs()
            .map(|output| {
                FusionTensor::new(
                    output.id,
                    output.shape.clone(),
                    output.dtype,
                    self.clone(),
                    StreamId::current(),
                )
            })
            .collect();

        // By doing this comparison, we reduce the number of bytes transferred in the device handle
        // queue.
        if size_of::<O>() < size_of::<UnfusedOp<R>>() {
            // Here the [`O`] type is smaller than the [`UnfusedOp`] type, so it's better to
            // transfer it directly.
            self.server.submit(move |server| {
                let operation = UnfusedOp::new(operation, streams.current);
                server.register(streams, repr, operation);
            });
        } else {
            // Here the [`O`] type is larger than the [`UnfusedOp`] type, so it's better to
            // first create the [`UnfusedOp`] before transferring it to the server.
            let operation = UnfusedOp::new(operation, streams.current);

            self.server.submit(move |server| {
                server.register(streams, repr, operation);
            });
        }

        outputs
    }

    /// Register all lazy computation.
    pub fn sync<Re: Send + 'static>(&self, sync_fn: impl FnOnce() -> Re + Send + 'static) -> Re {
        let id = StreamId::current();
        self.server
            .submit_blocking(move |server| {
                server.drain_stream(id);
                sync_fn()
            })
            .unwrap()
    }

    /// Flush the operations queue.
    pub fn flush_queue(&self) {
        self.server.flush_queue();
    }

    /// Create a new (uninitialized) empty tensor handle and returns its corresponding [tensor id](TensorId).
    pub fn create_empty_handle(&self) -> TensorId {
        let value = COUNTER.fetch_add(1, Ordering::Relaxed);
        TensorId::new(value)
    }

    /// Get the current device used by all operations handled by this client.
    pub fn device(&self) -> &FusionDevice<R> {
        &self.device
    }

    /// Create a tensor with the given handle and returns its corresponding [tensor id](TensorId).
    pub fn register_tensor_handle(&self, handle: FusionHandle<R>) -> TensorId {
        let id = self.create_empty_handle();

        self.server
            .submit(move |server| server.handles.register_handle(id, handle));

        id
    }

    /// Read the values contained by a float tensor.
    pub fn read_tensor_float<B>(
        self,
        tensor: TensorIr,
        stream: StreamId,
    ) -> impl Future<Output = Result<TensorData, ExecutionError>> + Send
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| server.float_data::<B>(tensor, stream))
            .unwrap()
    }

    /// Read the values contained by an int tensor.
    pub fn read_tensor_int<B>(
        self,
        tensor: TensorIr,
        stream: StreamId,
    ) -> impl Future<Output = Result<TensorData, ExecutionError>> + Send
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| server.int_data::<B>(tensor, stream))
            .unwrap()
    }

    /// Read the values contained by a bool tensor.
    pub fn read_tensor_bool<B>(
        self,
        tensor: TensorIr,
        stream: StreamId,
    ) -> impl Future<Output = Result<TensorData, ExecutionError>> + Send
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| server.bool_data::<B>(tensor, stream))
            .unwrap()
    }

    /// Read the values contained by a quantized tensor.
    pub fn read_tensor_quantized<B>(
        self,
        tensor: TensorIr,
        stream: StreamId,
    ) -> impl Future<Output = Result<TensorData, ExecutionError>> + Send
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| server.quantized_data::<B>(tensor, stream))
            .unwrap()
    }

    /// Change the client of the given float tensor.
    pub fn change_client_float<B>(
        tensor: TensorIr,
        client_src: Self,
        client_dst: Self,
        stream: StreamId,
    ) -> FusionTensor<R>
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        let dtype = tensor.dtype;
        let client_dst_cloned = client_dst.clone();
        let shape = tensor.shape.clone();
        let id = client_src.create_empty_handle();

        let float_tensor = client_src
            .server
            .submit_blocking(move |server_src| server_src.read_float::<B>(tensor, stream))
            .unwrap();
        let float_tensor = B::float_to_device(float_tensor, client_dst.device());
        client_dst.server.submit(move |server_dst| {
            server_dst
                .handles
                .register_float_tensor::<B>(&id, float_tensor.clone());
        });

        FusionTensor::new(id, shape, dtype, client_dst_cloned, StreamId::current())
    }

    /// Change the client of the given int tensor.
    pub fn change_client_int<B>(
        tensor: TensorIr,
        client_src: Self,
        client_dst: Self,
        stream: StreamId,
    ) -> FusionTensor<R>
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        let dtype = tensor.dtype;
        let client_dst_cloned = client_dst.clone();
        let shape = tensor.shape.clone();
        let id = client_src.create_empty_handle();

        let int_tensor = client_src
            .server
            .submit_blocking(move |server_src| server_src.read_int::<B>(tensor, stream))
            .unwrap();
        let int_tensor = B::int_to_device(int_tensor, client_dst.device());
        client_dst.server.submit(move |server_dst| {
            server_dst
                .handles
                .register_int_tensor::<B>(&id, int_tensor.clone());
        });

        FusionTensor::new(id, shape, dtype, client_dst_cloned, StreamId::current())
    }

    /// Change the client of the given bool tensor.
    pub fn change_client_bool<B>(
        tensor: TensorIr,
        client_src: Self,
        client_dst: Self,
        stream: StreamId,
    ) -> FusionTensor<R>
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        let dtype = tensor.dtype;
        let client_dst_cloned = client_dst.clone();
        let shape = tensor.shape.clone();
        let id = client_src.create_empty_handle();

        let bool_tensor = client_src
            .server
            .submit_blocking(move |server_src| server_src.read_bool::<B>(tensor, stream))
            .unwrap();
        let bool_tensor = B::bool_to_device(bool_tensor, client_dst.device());
        client_dst.server.submit(move |server_dst| {
            server_dst
                .handles
                .register_bool_tensor::<B>(&id, bool_tensor.clone());
        });

        FusionTensor::new(id, shape, dtype, client_dst_cloned, StreamId::current())
    }

    /// Change the client of the given quantized tensor.
    pub fn change_client_quantized<B>(
        tensor: TensorIr,
        client_src: Self,
        client_dst: Self,
        stream: StreamId,
    ) -> FusionTensor<R>
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        let dtype = tensor.dtype;
        let client_dst_cloned = client_dst.clone();
        let shape = tensor.shape.clone();
        let id = client_src.create_empty_handle();

        let q_tensor = client_src
            .server
            .submit_blocking(move |server_src| server_src.read_quantized::<B>(tensor, stream))
            .unwrap();
        let q_tensor = B::q_to_device(q_tensor, client_dst.device());
        client_dst.server.submit(move |server_dst| {
            server_dst
                .handles
                .register_quantized_tensor::<B>(&id, q_tensor.clone());
        });

        FusionTensor::new(id, shape, dtype, client_dst_cloned, StreamId::current())
    }

    /// Resolve the given float tensor to a primitive tensor.
    pub fn resolve_tensor_float<B>(&self, tensor: FusionTensor<R>) -> B::FloatTensorPrimitive
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| {
                server.drain_stream(tensor.stream);
                server.resolve_server_float::<B>(&tensor.into_ir())
            })
            .unwrap()
    }

    /// Resolve the given int tensor to a primitive tensor.
    pub fn resolve_tensor_int<B>(&self, tensor: FusionTensor<R>) -> B::IntTensorPrimitive
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| {
                server.drain_stream(tensor.stream);
                server.resolve_server_int::<B>(&tensor.into_ir())
            })
            .unwrap()
    }

    /// Resolve the given bool tensor to a primitive tensor.
    pub fn resolve_tensor_bool<B>(&self, tensor: FusionTensor<R>) -> B::BoolTensorPrimitive
    where
        B: FusionBackend<FusionRuntime = R>,
    {
        self.server
            .submit_blocking(move |server| {
                server.drain_stream(tensor.stream);
                server.resolve_server_bool::<B>(&tensor.into_ir())
            })
            .unwrap()
    }

    /// Synchronize the collective operations.
    #[cfg(feature = "distributed")]
    pub fn sync_collective<B>(&self, device: B::Device)
    where
        B: FusionBackend<FusionRuntime = R> + DistributedBackend,
    {
        // Ensure that all operations are resolved before calling sync_collective.
        self.drain();
        B::sync_collective(&device)
    }
}
