[default]
extend-ignore-identifiers-re = ["ratatui", "Ratatui", "NdArray*", "ND"]

[files]
extend-exclude = [
    "*.onnx",
    "assets/ModuleSerialization.xml",
    "examples/image-classification-web/src/model/label.txt",
    "examples/mnist-inference-android/gradle/*",
]

[default.extend-words]
# Don't correct "arange" which is intentional
arange = "arange"
