[cubecl.profiling]
logger = { log = "info", level = "disabled" }

[cubecl.autotune]
logger = { log = "info", level = "basic" }

[cubecl.compilation]
logger = { log = "info", level = "disabled" }
cache = "target"
