[package]
name = "gaba-native-kernels"
version = "0.1.0"
edition = "2021"

[features]
# When enabled, build.rs will attempt to compile the Zig kernel and link it.
zig = []
# Optional small SIMD implementations (AVX2 on x86_64, NEON on aarch64)
simd = []

[dependencies]
anyhow = "1.0"

[dev-dependencies]
approx = "0.5"

[package.metadata]
bench = true
