[package]
name = "burn-onnx-export"
description = "ONNX export support for Burn captured graphs"
edition.workspace = true
license.workspace = true
version.workspace = true
repository = "https://github.com/tracel-ai/burn"

[lints]
workspace = true

[dependencies]
burn-backend = { workspace = true }
burn-ir = { workspace = true }
burn-capture = { workspace = true }
burn-router = { workspace = true }
burn-core = { workspace = true }
burn-tensor = { workspace = true, features = ["capture", "extension"] }

bytes = { workspace = true }
hashbrown = { workspace = true }
thiserror = { workspace = true }
onnx-ir = { workspace = true }
protobuf = { workspace = true }

[dev-dependencies]
burn-nn = { workspace = true }
ort = { workspace = true }
tempfile = { workspace = true }
