[alias]
test-cpu = "test --release --no-default-features --features cpu,std,fusion"
test-cuda = "test --release --no-default-features --features cuda,std,fusion"
test-flex = "test --release --no-default-features --features flex,std"
test-ndarray = "test --release --no-default-features --features ndarray,std"
test-rocm = "test --release --no-default-features --features rocm,std,fusion"
# test-router = "test --release --no-default-features --features router,std"
test-tch = "test --release --no-default-features --features tch,std"
test-wgpu = "test --release --no-default-features --features wgpu,std,fusion"
test-vulkan = "test --release --no-default-features --features vulkan,std,fusion"
test-metal = "test --release --no-default-features --features metal,std,fusion"

# Fusion disabled tests
test-cpu-nofuse = "test --release --no-default-features --features cpu,std"
test-cuda-nofuse = "test --release --no-default-features --features cuda,std"
test-rocm-nofuse = "test --release --no-default-features --features rocm,std"
test-wgpu-nofuse = "test --release --no-default-features --features wgpu,std"
test-vulkan-nofuse = "test --release --no-default-features --features vulkan,std"
test-metal-nofuse = "test --release --no-default-features --features metal,std"
