[package]
name = "burn-import-model-checks-all-minilm-l6-v2"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[features]
default = ["tch"]
ndarray = []
tch = []
wgpu = []
metal = []

[dependencies]
burn = { path = "../../../../crates/burn", features = [
    "ndarray",
    "tch",
    "wgpu",
    "metal",
] }
burn-import = { path = "../../../burn-import", features = ["pytorch"] }

[build-dependencies]
burn-import = { path = "../../../burn-import" }
